sonar.organization=my-organization-test
# sonar.projectKey=cnlucas_fec-cms

# Python specific settings
sonar.python.version=3.11

# Exclusions
# sonar.exclusions=

# sonar.host.url=https://sonarcloud.io
